### ISSUE TITLE
Getting "null data attribute" error while sending pldm command over ncsi transport.

### ISSUE THREAD

**Issue by HCL-BMC** [openbmc/pldm#23]
We are working on NIC firmware update over NCSI transport for our platform.

We are creating an application code and using libncsi library to send the commands to the NIC cards.
Got the correct response for first command, "Request update".

Getting the "Null data attribute" error while sending second command "Pass Component Table".

Note : The same application code are working with Raw Socket  and we could able to do NIC firmware update.

Could you please provide if any suggestions/help. 
[pldm_error.txt](https://github.com/openbmc/pldm/files/6599291/pldm_error.txt)

**Comment by manojkiraneda** [comment]
@HCL-BMC there are a lot of commands related to firmware update that are still pending in review (https://gerrit.openbmc-project.xyz/q/owner:gokul.sanker.v.g%2540intel.com)

As far as i see "Pass Component Table" cmd support in libpldm (https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/41833) is still not merged.

Please feel free to hop over to gerrit and help review those patch-sets to get it merged faster.

**Comment by HCL-BMC** [comment]
@manojkiraneda ,  

       I have created our own libpldm encode and decode functions for all the NIC firmware update commands.

      The encode/decode functions created by us are working fine with the Raw socket code. 

       But it is not working with the NSCI transport. Getting "Null data Attribute" Error for PassCompTable command.

      Please find the attached encode/decode functions for PassCompTable Command.
      
[PassCompTable_functions.txt](https://github.com/openbmc/pldm/files/6604531/PassCompTable_functions.txt)


Thanks,
Kumar.

**Comment by tomjoseph83** [comment]
@HCL-BMC 

Hello Kumar,

From the problem statement it looks like to be a transport issue, since the code works fine with raw sockets. Which NC-SI over MCTP channel implementation are you leveraging? "Getting "Null data Attribute" Error for PassCompTable command." This maps to which ComponentResponseCode? I think the content provided here is not sufficient to help in debug.

Since this is not related to implementation available in this repository, we can close this issue. Meanwhile if you can share the implementation and reachout on OpenBMC discord channel #mctp-and-pldm. We can get the attention of OpenBMC community members.

Regards,
Tom

**Comment by HCL-BMC** [comment]
@tomjoseph83 , 

Thanks Tom for your response. 
I will share the details with discord #mctp-pldm channel. 

Thanks,
Kumar.
